#Jeffrey Minton
#Computer Science Masters Thesis Software
#Advisor: Dr. Oskars Rieksts

INCLUDE_PATH = "C:\Program Files\MATLAB\R2010a Student\extern\include"

build:
	g++ -v -o diabot.exe diabot.cpp
